jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cone
      - name: Clone
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
      - name: Install
        run: npm ci
      - name: Run tests
        run: npx ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI
      - name: run tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
